global:
  resolve_timeout: 5m

route:
  receiver: default-null
  group_by: ["alertname", "kind"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers:
        - severity="critical"
      receiver: paged
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 1h
    - matchers:
        - severity="warning"
      receiver: default-null
      group_wait: 1m
      group_interval: 10m
      repeat_interval: 12h

receivers:
  - name: default-null
  - name: paged
    webhook_configs:
      - url: http://ntfy-adapter:8080/
        send_resolved: true
    pagerduty_configs:
      - routing_key_file: /etc/alertmanager/secrets/pagerduty_routing_key
        send_resolved: true
