{
 "title": "Node Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Target Up",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\"}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance_name) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  }
 ]
}